# https://taskfile.dev

version: '3'

output: 'prefixed'

vars:
  UrlExe: url{{exeExt}} 

tasks:
  default:
    desc: list tasks
    cmds:
      - task -l
    silent: true

  run:
    desc: run web server
    cmds:
      - DATABASE_URL=postgres://postgres:123456@localhost:5432/url APP_ADMIN_TOKEN=abcd go run main.go
    silent: false

  prod:
    desc: product 
    cmds:
      - APP_ENV=prod DATABASE_URL=postgres://postgres:123456@localhost:5432/url APP_ADMIN_TOKEN=abcd go run main.go 
    silent: false

  release:
    desc: release
    cmds:
      - GOOS=linux go build -o ./release/{{.UrlExe}} -ldflags="-w -s" main.go  
    silent: false
