# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: list tasks
    cmds:
      - task -l
    silent: true

  run:
    desc: run web server
    cmds:
      - DATABASE_URL=postgres://postgres:123456@localhost:5432/urlsh go run main.go
    silent: false
